services:
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: unless-stopped

    ports:
      - "8080:8080"

    environment:
      KAFKA_CLUSTERS_0_NAME: Production

      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: YOUR_SERVER_IP:9092

      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_PLAINTEXT

      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: PLAIN

      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: >
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="billing"
        password="BillingPassword123";
